version: "3.3"
services:
  generator:
    image: "ilcsoft/py3lcio:lcio-15-04_v3"
    volumes:
       - ~/synthetic-data-generator:/home/ilc/datagen
    command: >
      bash -c "source datagen/set_env.sh 
      && cd datagen 
      && streamlit run generator.py -- --output wgantest.slcio --nbsize 100" 
    ports:
      - "8501:8501"
  reco:
    image: "ilcsoft/ilcsoft-centos7-gcc8.2:v02-01-pre"
    command: ./reconstruction/marlin-reco.sh wgantest.slcio
    volumes:
       - ~/synthetic-data-generator:/home/ilc/iLCInstall/ilcsoft
